### ISSUE TITLE
CLI raising error on email validation

### ISSUE THREAD

**Issue by abdalem** [Infisical/infisical#25]
HI. I have an issue about email validation when installing the new CLI. It raise an exception on my email that ending with `.tech` domain. The exception thrown is the following: `>> this doesn't look like an email address`

**Comment by maidul98** [comment]
Hello! I have updated the regex to be a bit more accurate when validating the email address. 

For reference here is the code i pushed to update it: https://github.com/Infisical/infisical/commit/3689d75bdedfc7a26b99ee4f34ae50225b54eea0

I have also pushed out a new release: https://github.com/Infisical/infisical/actions/runs/3514837815

Once the release is complete, you may reinstall or update the CLI in your package manager to receive the new change. Please let us know if you continue to have trouble.

**Comment by abdalem** [comment]
Great ! The email regex is actually passing, but still having an issue for login: `Unable to store your credentials in system key ring`

I am using Ubuntu through WSL if that helps. WIth the old CLI (node), I had not any issue on login with the same platform.

**Comment by maidul98** [comment]
The Keyring is used to store your login credentials securely at rest. This must be because you are on a headless Linux on WSL where keyring may not be available. I'm going to work on reproducing this bug and seeing how we can get keyring on your Linux. I will get back to this shortly

**Comment by maidul98** [comment]
I was able to reproduce the issue you mentioned. This is because you are on a headless linux (WSL). Here is my recommendation if you want to continue using WSL. 

Since WSL 

1. Install the Keyring on WSL

 
```
sudo apt-get update -y

sudo apt-get install -y gnome-keyring
```

2. install the CLI (i think you have done that already)

3. start Keyring
```
export $(dbus-launch)
gnome-keyring-daemon -r --unlock --components=secrets
```
Note: The command `gnome-keyring-daemon -r --unlock --components=secrets` expects you to type your WSL password. Once you entered your password, press Ctrl+D twice.

4. Login to infisical 
```
infisical login 
```

Please keep in mind that you will have to run step 3 each time you open a terminal which did not already have the Keyring unlocked. Otherwise, you will get the same error. You do not have to login again after you successfully logged in once. You will just have to run step 2 in the terminal at least once before you run infisical. 

Typically, all of this already exists on your system if you have a full linux/windows/mac so you don't have to do anything other than login into infisical. Let me know if this helps.

**Comment by abdalem** [comment]
Ok ! Thanks ! I will try to find a solution to bypass this. Lot of people are using WSL now, including my whole teams.

**Comment by maidul98** [comment]
I'm working on adding other options to store your credentials in case you do not have Keyring for your system. Hopefully once that is our, it should be much smoother for you. I will provide updates here

**Comment by maidul98** [comment]
If you’ve had issues logging in because of keyring problems, Infisical CLI now supports multiple vaults to save your login credentials at rest. That means if the default store doesn’t work, you can switch to a different vault. Or, if you don’t have any vaults installed at all, you can still store your credentials safely in an encrypted text file with a passphrase that only you know. Check out more info on this here https://infisical.com/docs/cli/commands/vault don’t forget to update your CLI!
