### ISSUE TITLE
Issue with Personal Overrides

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#899]
Hey Infisical Team - I know for sure the personal overrides used to work. I'm now having trouble setting a personal override. Everything seems right from the Dashboard. Here's what I did:

1. Navigated to the secrets dashboard for the `dev` env
2. Used the search bar to filter to my desired secret
3. Clicked the "branch icon" to override with my personal value
4. Typed in the new value
5. Clicked Save Changes
6. I now see the branch green, but my CLI and app are not seeing my overridden value: they see the shared value. I even tried relogging into infisical
7. Clicking the three dot menu shows that the "Override with personal value" toggle is *unchecked*, but it appears to have the value?
    a. I even tried setting the toggle to on, saving the changes in the drawer, and reloading the page: it had reset the override toggle
Any ideas?

[Slack Message](https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1693003347198399?thread_ts=1693003347.198399&cid=C04BSBMQAQ7)

**Comment by ngavin** [comment]
Following

**Comment by dangtony98** [comment]
I think this issue is resolved with the latest CLI update; the issue was that the CLI was displaying all `shared` secret values even for the `personal`/`overridden` ones; it should now be showing the correct value.

Regarding injection, the secret overrides should be working as expected.

**Comment by ngavin** [comment]
Hi @dangtony98 - I upgraded the Infisical CLI today and am still seeing the issue. Note I am on Windows and installing via Scoop:

![image](https://github.com/Infisical/infisical/assets/6372187/d6e95f93-31ee-4a33-af97-8b280b64d878)

The injected secrets are not working either. I am seeing functionality that should be disabled with my personal override happen. I have restarted my app.

The Infisical Dashboard UI is also still not correct. Note how the personal override icon is visible in the dashboard, but the drawer does not correspond:

![image](https://github.com/Infisical/infisical/assets/6372187/44dc1d53-caf7-4325-8244-b27323f775f5)

**Comment by maidul98** [comment]
Working on reproducing this on my end

**Comment by decarbonise** [comment]
I'm having the same issue with the Python SDK. get_all_secrets is returning only the shared values, rather than personal overrides.

**Comment by dangtony98** [comment]
@decarbonise Let me check if this is a Python SDK-specific issue or not.

We're aware of a frontend issue related to secret overrides being flaky at the moment and are pushing out a patch for that soon.

**Comment by decarbonise** [comment]
Thanks @dangtony98. Steps to reproduce for me are:
- Add secrets to prod and override them
- Request all_secrets through the Python SDK, environment=prod
- See that returned result has neither overrides nor substitutions (e.g. has literal $(dev.MY_VAR))

I've just tried with the CLI and that seems okay for now

**Comment by decarbonise** [comment]
Hmm. Weirdly now some personal values are showing up in Python and some aren't (they're showing as shared). Yet when I run the same thing with the same token in the CLI, everything displays correctly

**Comment by ngavin** [comment]
Any progress on this case?

**Comment by maidul98** [comment]
We released a fix for properly updating the value of override on the UI side. Can you check to see if the same issue still occurs?

**Comment by ngavin** [comment]
Hi @maidul98 - I just tried again and it is still not working.

I tried hard reloading the Infisical web UI. I then reset my personal override, changed the shared value to a new test value, and then changed it to the original (to ensure we have a solid base for the personal overried). I then tried to set a personal override both via the "branch" icon and the three dot menu.

In both cases, the secrets grid showed I had a personal override, but the three dot menu side panel did NOT show it - it had the toggle unchecked. In my CLI, I am still getting the shared value. I have updated my cli to the latest (v 0.12.1 on Windows)

**Comment by ngavin** [comment]
Hi @maidul98 - Thanks for all the help so far. Was there any movement on this ticket this week?

**Comment by akhilmhdh** [comment]
Hey @ngavin can you try now and update us

**Comment by ngavin** [comment]
@akhilmhdh It works now - Thanks!
